### ISSUE TITLE
Table output and graphs broken in HTML output due to MINLEN

### ISSUE THREAD

**Issue by nishihatapalmer** [smart-tool/smart#11]
The HTML results are broken in the following ways:

* The table displays columns where there are no results (string length = 0)
* The graphs do not display correctly, with pop ups saying there are negative values.

**Comment by nishihatapalmer** [comment]
Fixed by #12 - but that PR also includes the QF fixes.

To resolve this issue, just set MINLEN to 1 in smart.c

**Comment by nishihatapalmer** [comment]
Closed original PR as it contained other fixes by mistake.  But as I say, you don't really need a PR for this - it's changing a single digit from 0 to 1 in `smart.c`.

**Comment by Helias** [comment]
do you mean this? https://github.com/smart-tool/smart/pull/12/commits/01cb88ca7af7105101fd5203747fe0b04f12a855

**Comment by nishihatapalmer** [comment]
Yes, that's the commit.

**Comment by nishihatapalmer** [comment]
I have reviewed all the usages of MINLEN in the code, and all tests are  `>= MINLEN`, so setting to 1 should not prevent lengths of 1 being properly processed.
For user supplied values, a `MINLEN < 1` is flagged as an input parameter error.
So it seems reasonable that MINLEN should be 1, not 0.

**Comment by Helias** [comment]
I trust you, done ✅

**Comment by nishihatapalmer** [comment]
note: I have found that this doesn't entirely fix the negative value popups from the graphs, although it helps.
