### ISSUE TITLE
Results of testing algorithms

### ISSUE THREAD

**Issue by zamazan4ik** [smart-tool/smart#2]
Hello. 

Are there any results of testing all algorithms on data? It will be very useful for me.

Thanks!

**Comment by simonefaro** [comment]
Dear Alexander,
please find here (http://arxiv.org/abs/1012.2547) a comprehensive
experimental evaluation of all string matching algorithms, updated to 2011.
However some new algorithms have been presented in the last few years.
You can find the new experimental results directly inside the papers
presenting the new solutions.
See for instance:
http://link.springer.com/chapter/10.1007%2F978-3-319-41168-2_6

All the best
Simone

2016-10-25 0:21 GMT+02:00 Alexander notifications@github.com:
