### ISSUE TITLE
Some data settings are missing 

### ISSUE THREAD

**Issue by stefan-it** [smart-tool/smart#3]
Hi,

in `source/sets.h` the following data folders are set in `*SETTING_BUFFER` which are missing in the `data` folder:

* `frenchTexts`
* `chineseTexts`
* `midimusic`

That leads to the following error message when executing `./smart -text all`:

```bash
Try to process archive frenchTexts
	Error in loading text buffer. No index file exists.
	Alphabet of 0 characters.
	Greater chararacter has code 0.
```

If you want I can create a PR to remove these settings :)

**Comment by simonefaro** [comment]
Hi,
missing data were added and are now available in the repository.
You can find them inside the data/ main directory
