### ISSUE TITLE
https://www.dmi.unict.it/~faro/smart/howto.php - Not found.

### ISSUE THREAD

**Issue by patelakash317** [smart-tool/smart#6]

**Comment by nishihatapalmer** [comment]
Agreed - link to documentation on how to use SMART is broken.  Please fix.
The old documentation can still be found in the Internet Archive here:

https://web.archive.org/web/20200420023139/https://www.dmi.unict.it/~faro/smart/howto.php

**Comment by Helias** [comment]
Link fixed, thanks for the report
